In [1]:
""" RUN THIS CELL TO GET THE RIGHT FORMATTING """
import requests
from IPython.core.display import HTML
css_file = 'https://raw.githubusercontent.com/bsethwalker/clemson-cs4300/main/css/cpsc6300.css'
styles = requests.get(css_file).text
HTML(styles)

In [2]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
pd.set_option('display.width', 500)
pd.set_option('display.max_columns', 100)

In [10]:
import os
# This lists all files in the current directory
os.listdir()

['.config', 'sample_data']

In [11]:
%cd sample_data

/content/sample_data

In [14]:
#Read the data into a dataframe
df = pd.read_csv("goodreads.csv", encoding='utf-8')

#Examine the first few rows of the dataframe
df

      4.40   136455  0439023483  good_reads:book https://www.goodreads.com/author/show/153394.Suzanne_Collins    2008 /genres/young-adult|/genres/science-fiction|/genres/dystopia|/genres/fantasy|/genres/science-fiction|/genres/romance|/genres/adventure|/genres/book-club|/genres/young-adult|/genres/teen|/genres/apocalyptic|/genres/post-apocalyptic|/genres/action                dir01/2767052-the-hunger-games.html    2958974            The Hunger Games (The Hunger Games, #1)
0     4.41  16648.0  0439358078  good_reads:book  https://www.goodreads.com/author/show/1077326....            2003.0  /genres/fantasy|/genres/young-adult|/genres/fi...                                                                                                                                                                                                     dir01/2.Harry_Potter_and_the_Order_of_the_Phoe...  1284478.0  Harry Potter and the Order of the Phoenix (Har...
1     3.56  85746.0  0316015849  good_reads:book  https://www.goodreads.com/author/show/941441.S...            2005.0  /genres/young-adult|/genres/fantasy|/genres/ro...                                                                                                                                                                                                                             dir01/41865.Twilight.html  2579564.0                            Twilight (Twilight, #1)
2     4.23  47906.0  0061120081  good_reads:book  https://www.goodreads.com/author/show/1825.Har...            1960.0  /genres/classics|/genres/fiction|/genres/histo...                                                                                                                                                                                                                 dir01/2657.To_Kill_a_Mockingbird.html  2078123.0                              To Kill a Mockingbird
3     4.23  34772.0  0679783261  good_reads:book  https://www.goodreads.com/author/show/1265.Jan...            1813.0  /genres/classics|/genres/fiction|/genres/roman...                                                                                                                                                                                                                   dir01/1885.Pride_and_Prejudice.html  1388992.0                                Pride and Prejudice
4     4.25  12363.0  0446675539  good_reads:book  https://www.goodreads.com/author/show/11081.Ma...            1936.0  /genres/classics|/genres/historical-fiction|/g...                                                                                                                                                                                                                   dir01/18405.Gone_with_the_Wind.html   645470.0                                 Gone with the Wind
...    ...      ...         ...              ...                                                ...               ...                                                ...                                                                                                                                                                                                                                                   ...        ...                                                ...
5994  4.17   2226.0  0767913736  good_reads:book  https://www.goodreads.com/author/show/44565.Ca...            2005.0  /genres/history|/genres/non-fiction|/genres/bi...                                                                                                                                                                                                                   dir60/78508.The_River_of_Doubt.html    16618.0                                 The River of Doubt
5995  3.99    775.0  1416909427  good_reads:book  https://www.goodreads.com/author/show/151371.J...            2006.0  /genres/young-adult|/genres/realistic-fiction|...                                                                                                                                                                                                                                dir60/259068.Shug.html     6179.0                                               Shug
5996  3.78    540.0  1620612321  good_reads:book  https://www.goodreads.com/author/show/5761314....            2012.0  /genres/contemporary|/genres/romance|/genres/y...                                                                                                                                                                                                                            dir60/13503247-flawed.html     2971.0                                             Flawed
5997  3.91    281.0         NaN  good_reads:book  https://www.goodreads.com/author/show/1201952....            2006.0  /genres/religion|/genres/islam|/genres/religio...                                                                                                                                                                                                                                    dir60/2750008.html     3083.0              Ø£Ø³Ø¹Ø¯ Ø§Ù
Ø±Ø£Ø© ÙÙ Ø§ÙØ¹Ø§ÙÙ

5998  4.35     61.0  0786929081  good_reads:book  https://www.goodreads.com/author/show/1023510....            2001.0  /genres/fiction|/genres/fantasy|/genres/magic|...                                                                                                                                                                                                     dir60/66677.Legacy_of_the_Drow_Collector_s_Edi...     3982.0  Legacy of the Drow Collector's Edition (Legacy...

[5999 rows x 10 columns]

Oh dear. That does not quite seem to be right. We are missing the column names. We need to add these in! But what are they?

Here is a list of them in order:

["rating", 'review_count', 'isbn', 'booktype','author_url', 'year', 'genre_urls', 'dir','rating_count', 'name']

Exercise
Use these to load the dataframe properly! And then "head" the dataframe... (you will need to look at the read_csv docs)

In [15]:
# your code here
df = pd.read_csv("goodreads.csv", header=None,
                 names=["rating", 'review_count', 'isbn', 'booktype','author_url', 'year', 'genre_urls', 'dir','rating_count', 'name'],
)

#Examine the first few rows of the dataframe
df.tail()

      rating  review_count        isbn         booktype                                         author_url    year                                         genre_urls                                                dir  rating_count                                               name
5995    4.17        2226.0  0767913736  good_reads:book  https://www.goodreads.com/author/show/44565.Ca...  2005.0  /genres/history|/genres/non-fiction|/genres/bi...                dir60/78508.The_River_of_Doubt.html       16618.0                                 The River of Doubt
5996    3.99         775.0  1416909427  good_reads:book  https://www.goodreads.com/author/show/151371.J...  2006.0  /genres/young-adult|/genres/realistic-fiction|...                             dir60/259068.Shug.html        6179.0                                               Shug
5997    3.78         540.0  1620612321  good_reads:book  https://www.goodreads.com/author/show/5761314....  2012.0  /genres/contemporary|/genres/romance|/genres/y...                         dir60/13503247-flawed.html        2971.0                                             Flawed
5998    3.91         281.0         NaN  good_reads:book  https://www.goodreads.com/author/show/1201952....  2006.0  /genres/religion|/genres/islam|/genres/religio...                                 dir60/2750008.html        3083.0              Ø£Ø³Ø¹Ø¯ Ø§Ù
Ø±Ø£Ø© ÙÙ Ø§ÙØ¹Ø§ÙÙ

5999    4.35          61.0  0786929081  good_reads:book  https://www.goodreads.com/author/show/1023510....  2001.0  /genres/fiction|/genres/fantasy|/genres/magic|...  dir60/66677.Legacy_of_the_Drow_Collector_s_Edi...        3982.0  Legacy of the Drow Collector's Edition (Legacy...

In [16]:
df.columns = ["rating", 'review_count', 'isbn', 'booktype','author_url', 'year', 'genre_urls', 'dir','rating_count', 'name']
df.head()

   rating  review_count        isbn         booktype                                         author_url    year                                         genre_urls                                                dir  rating_count                                               name
0    4.40      136455.0  0439023483  good_reads:book  https://www.goodreads.com/author/show/153394.S...  2008.0  /genres/young-adult|/genres/science-fiction|/g...                dir01/2767052-the-hunger-games.html     2958974.0            The Hunger Games (The Hunger Games, #1)
1    4.41       16648.0  0439358078  good_reads:book  https://www.goodreads.com/author/show/1077326....  2003.0  /genres/fantasy|/genres/young-adult|/genres/fi...  dir01/2.Harry_Potter_and_the_Order_of_the_Phoe...     1284478.0  Harry Potter and the Order of the Phoenix (Har...
2    3.56       85746.0  0316015849  good_reads:book  https://www.goodreads.com/author/show/941441.S...  2005.0  /genres/young-adult|/genres/fantasy|/genres/ro...                          dir01/41865.Twilight.html     2579564.0                            Twilight (Twilight, #1)
3    4.23       47906.0  0061120081  good_reads:book  https://www.goodreads.com/author/show/1825.Har...  1960.0  /genres/classics|/genres/fiction|/genres/histo...              dir01/2657.To_Kill_a_Mockingbird.html     2078123.0                              To Kill a Mockingbird
4    4.23       34772.0  0679783261  good_reads:book  https://www.goodreads.com/author/show/1265.Jan...  1813.0  /genres/classics|/genres/fiction|/genres/roman...                dir01/1885.Pride_and_Prejudice.html     1388992.0                                Pride and Prejudice

Cleaning: Examing the dataframe - quick checks
We should examine the dataframe to get a overall sense of the content.

Exercise
Lets check the types of the columns. What do you find?

In [17]:
# your code here
#######
df.dtypes
#######

rating          float64
review_count    float64
isbn             object
booktype         object
author_url       object
year            float64
genre_urls       object
dir              object
rating_count    float64
name             object
dtype: object

In [18]:
print(df.shape)
df.columns

(6000, 10)

Index(['rating', 'review_count', 'isbn', 'booktype', 'author_url', 'year', 'genre_urls', 'dir', 'rating_count', 'name'], dtype='object')

Cleaning: Examining the dataframe - a deeper look
Beyond performing checking some quick general properties of the data frame and looking at the first  n  rows, we can dig a bit deeper into the values being stored. If you haven't already, check to see if there are any missing values in the data frame.

Let's see for a column which seemed OK to us.

In [19]:
#Get a sense of how many missing values there are in the dataframe.
print(np.sum([df.rating.isnull()]))
print(np.sum([df.review_count.isnull()]))
print(np.sum([df.isbn.isnull()]))
print(np.sum([df.booktype.isnull()]))
print(np.sum([df.author_url.isnull()]))
print(np.sum([df.year.isnull()]))
print(np.sum([df.genre_urls.isnull()]))
print(np.sum([df.dir.isnull()]))
print(np.sum([df.rating_count.isnull()]))
print(np.sum([df.name.isnull()]))

2
2
477
2
2
7
62
0
2
2

In [20]:
#Try to locate where the missing values occur
df[df.rating.isnull()]

      rating  review_count isbn booktype author_url  year genre_urls                              dir  rating_count name
3643     NaN           NaN  NaN      NaN        NaN   NaN        NaN  dir37/9658936-harry-potter.html           NaN  NaN
5282     NaN           NaN  NaN      NaN        NaN   NaN        NaN     dir53/113138.The_Winner.html           NaN  NaN

How does pandas or numpy handle missing values when we try to compute with data sets that include them?

We'll now check if any of the other suspicious columns have missing values. Let's look at year and review_count first.

One thing you can do is to try and convert to the type you expect the column to be. If something goes wrong, it likely means your data are bad.

Lets test for missing data:

In [21]:
df[df.year.isnull()]

df.year.isnull()
df.shape

(6000, 10)

Cleaning: Dealing with Missing Values
How should we interpret 'missing' or 'invalid' values in the data (hint: look at where these values occur)? One approach is to simply exclude them from the dataframe. Is this appropriate for all 'missing' or 'invalid' values?

In [22]:
#Treat the missing or invalid values in your dataframe
#######

df = df[df.year.notnull()]

In [23]:
df.dtypes

rating          float64
review_count    float64
isbn             object
booktype         object
author_url       object
year            float64
genre_urls       object
dir              object
rating_count    float64
name             object
dtype: object

In [24]:
print(np.sum(df.year.isnull()))
df.shape # We removed seven rows

0

(5993, 10)

<div class="exercise"><b>Exercise</b></div>

Ok so lets fix those types. Convert them to ints. If the type conversion fails, we now know we have further problems.

In [25]:
# your code here
df.rating_count = df.rating_count.astype(int)
df.review_count = df.review_count.astype(int)
df.year = df.year.astype(int)

Once you do this, we seem to be good on these columns (no errors in conversion). Lets look:

In [26]:
df.dtypes

rating          float64
review_count      int64
isbn             object
booktype         object
author_url       object
year              int64
genre_urls       object
dir              object
rating_count      int64
name             object
dtype: object

In [27]:
df.loc[df.genre_urls.isnull(), 'genre_urls']=""
df.loc[df.isbn.isnull(), 'isbn']=""

**Part 2: Parsing and Completing the Data Frame**
We will parse the author column from the author_url and genres column from the genre_urls. Keep the genres column as a string separated by '|'.

We will use panda's map to assign new columns to the dataframe.

Examine an example author_url and reason about which sequence of string operations must be performed in order to isolate the author's name.

In [28]:
#Get the first author_url
test_string = df.author_url[0]
test_string

'https://www.goodreads.com/author/show/153394.Suzanne_Collins'

In [29]:
#Test out some string operations to isolate the author name

test_string.split('/')[-1].split('.')[1:][0]

'Suzanne_Collins'

Exercise
Lets wrap the above code into a function which we will then use

In [31]:
# Write a function that accepts an author url and returns the author's name based on your experimentation above
def get_author(url):
    # your code here
    name = url.split('/')[-1].split('.')[1:][0]

    return name

In [32]:
#Apply the get_author function to the 'author_url' column using '.map'
#and add a new column 'author' to store the names
df['author'] = df.author_url.map(get_author)
df.author[0:5]

0    Suzanne_Collins
1        J_K_Rowling
2    Stephenie_Meyer
3         Harper_Lee
4        Jane_Austen
Name: author, dtype: object

Now parse out the genres from genre_url.

This is a little more complicated because there be more than one genre.

In [33]:
df.genre_urls.head()

0    /genres/young-adult|/genres/science-fiction|/g...
1    /genres/fantasy|/genres/young-adult|/genres/fi...
2    /genres/young-adult|/genres/fantasy|/genres/ro...
3    /genres/classics|/genres/fiction|/genres/histo...
4    /genres/classics|/genres/fiction|/genres/roman...
Name: genre_urls, dtype: object

In [34]:
# your code here
#Examine some examples of genre_urls

#Test out some string operations to isolate the genre name
test_genre_string=df.genre_urls[0]
genres=test_genre_string.strip().split('|')
for e in genres:
    print(e.split('/')[-1])
    "|".join(genres)

young-adult
science-fiction
dystopia
fantasy
science-fiction
romance
adventure
book-club
young-adult
teen
apocalyptic
post-apocalyptic
action

Exercise
Write a function that accepts a genre url and returns the genre name based on your experimentation above

In [42]:
def split_and_join_genres(url):
    # your code here
    genres = url.split('|')
    return '|'.join([genre.split('/')[-1] for genre in genres])

In [43]:
split_and_join_genres("/genres/young-adult|/genres/science-fiction")

'young-adult|science-fiction'

In [44]:
split_and_join_genres("")

''

Exercise
Use map again to create a new "genres" column

In [45]:
df['genres'] = df.genre_urls.map(split_and_join_genres)
df.head()

   rating  review_count        isbn         booktype                                         author_url  year                                         genre_urls                                                dir  rating_count                                               name           author                                             genres
0    4.40        136455  0439023483  good_reads:book  https://www.goodreads.com/author/show/153394.S...  2008  /genres/young-adult|/genres/science-fiction|/g...                dir01/2767052-the-hunger-games.html       2958974            The Hunger Games (The Hunger Games, #1)  Suzanne_Collins  young-adult|science-fiction|dystopia|fantasy|s...
1    4.41         16648  0439358078  good_reads:book  https://www.goodreads.com/author/show/1077326....  2003  /genres/fantasy|/genres/young-adult|/genres/fi...  dir01/2.Harry_Potter_and_the_Order_of_the_Phoe...       1284478  Harry Potter and the Order of the Phoenix (Har...      J_K_Rowling  fantasy|young-adult|fiction|fantasy|magic|chil...
2    3.56         85746  0316015849  good_reads:book  https://www.goodreads.com/author/show/941441.S...  2005  /genres/young-adult|/genres/fantasy|/genres/ro...                          dir01/41865.Twilight.html       2579564                            Twilight (Twilight, #1)  Stephenie_Meyer  young-adult|fantasy|romance|paranormal|vampire...
3    4.23         47906  0061120081  good_reads:book  https://www.goodreads.com/author/show/1825.Har...  1960  /genres/classics|/genres/fiction|/genres/histo...              dir01/2657.To_Kill_a_Mockingbird.html       2078123                              To Kill a Mockingbird       Harper_Lee  classics|fiction|historical-fiction|academic|s...
4    4.23         34772  0679783261  good_reads:book  https://www.goodreads.com/author/show/1265.Jan...  1813  /genres/classics|/genres/fiction|/genres/roman...                dir01/1885.Pride_and_Prejudice.html       1388992                                Pride and Prejudice      Jane_Austen  classics|fiction|romance|historical-fiction|li...

Finally, let's pick an author at random so we can see the results of the transformations. Scroll to see the author and genre columns that we added to the dataframe.

In [46]:
df[df.author == "Marguerite_Yourcenar"]

      rating  review_count        isbn         booktype                                         author_url  year                                         genre_urls                                  dir  rating_count                name                author                                             genres
1014    4.23           483  0374529264  good_reads:book  https://www.goodreads.com/author/show/7732.Mar...  1951  /genres/historical-fiction|/genres/fiction|/ge...  dir11/12172.Memoirs_of_Hadrian.html          6258  Memoirs of Hadrian  Marguerite_Yourcenar  historical-fiction|fiction|cultural|france|cla...
5620    4.11            74  2070367983  good_reads:book  https://www.goodreads.com/author/show/7732.Mar...  1968  /genres/fiction|/genres/historical-fiction|/ge...     dir57/953435.L_uvre_au_noir.html          1601    L'Åuvre au noir  Marguerite_Yourcenar  fiction|historical-fiction|cultural|france|eur...

In [47]:
df = df.drop('genre_urls', axis=1)

In [49]:
df.to_csv("cleaned-goodreads.csv", index=False, header=True)

**Part 3: Grouping**
It appears that some books were written in negative years! Print out the observations that correspond to negative years. What do you notice about these books?

In [50]:
# your code here
df[df.year < 0].name
#These are books written before the Common Era (BCE, equivalent to BC).

47                               The Odyssey
246                    The Iliad/The Odyssey
455                             The Republic
596                               The Aeneid
629                              Oedipus Rex
674                           The Art of War
746                        The Bhagavad Gita
777                                 Antigone
1233                       The Oedipus Cycle
1397                          Aesop's Fables
1398                   The Epic of Gilgamesh
1428                                   Medea
1815                            The Oresteia
1882         The Trial and Death of Socrates
2078    The History of the Peloponnesian War
2527                           The Histories
3133                          Complete Works
3274                  The Nicomachean Ethics
3757                              Lysistrata
4402                           The Symposium
4475                                 Apology
5367                          Five Dialogues
Name: name, dtype: object

We can determine the "best book" by year! For this we use Panda's groupby(). Groupby() allows grouping a dataframe by any (usually categorical) variable. Would it make sense to ever groupby integer variables? Floating point variables?

In [51]:
dfgb_author = df.groupby('author')
type(dfgb_author)

pandas.core.groupby.generic.DataFrameGroupBy

In [52]:
dfgb_author.count()

                       rating  review_count  isbn  booktype  author_url  year  dir  rating_count  name  genres
author
A_A_Milne                   6             6     6         6           6     6    6             6     6       6
A_G_Howard                  1             1     1         1           1     1    1             1     1       1
A_J_Cronin                  1             1     1         1           1     1    1             1     1       1
A_J_Jacobs                  1             1     1         1           1     1    1             1     1       1
A_J_Salt                    1             1     1         1           1     1    1             1     1       1
...                       ...           ...   ...       ...         ...   ...  ...           ...   ...     ...
_                          42            42    42        42          42    42   42            42    42      42
_gota_Krist_f               1             1     1         1           1     1    1             1     1       1
_mile_Zola                  4             4     4         4           4     4    4             4     4       4
_ric_Emmanuel_Schmitt       1             1     1         1           1     1    1             1     1       1
_sne_Seierstad              1             1     1         1           1     1    1             1     1       1

[2645 rows x 10 columns]

**Exercise:**
Group the dataframe by author. Include the following columns: rating, name, author. For the aggregation of the name column which includes the names of the books create a list with the strings containing the name of each book. Make sure that the way you aggregate the rest of the columns make sense!

Create a new column with number of books for each author and find the most prolific author!

In [53]:
###### Before we start : what do we do about these titles where 'name' is unreadable? Try different encodings?
auth_name = 'A_id_al_Qarni'
df[df.author == auth_name].head()

      rating  review_count isbn         booktype                                         author_url  year                 dir  rating_count                                   name         author                                             genres
2213    4.19          1169       good_reads:book  https://www.goodreads.com/author/show/1201952....  2003  dir23/2750180.html         15781                          ÙØ§ ØªØ­Ø²Ù  A_id_al_Qarni  religion|religion|islam|self-help|non-fiction|...
5998    3.91           281       good_reads:book  https://www.goodreads.com/author/show/1201952....  2006  dir60/2750008.html          3083  Ø£Ø³Ø¹Ø¯ Ø§Ù
Ø±Ø£Ø© ÙÙ Ø§ÙØ¹Ø§ÙÙ
  A_id_al_Qarni  religion|islam|religion|self-help|spirituality...

In [54]:
df[df.author == auth_name].iat[0,8].encode('UTF-16')

b'\xff\xfe\xd9\x00\x84\x00\xd8\x00\xa7\x00 \x00\xd8\x00\xaa\x00\xd8\x00\xad\x00\xd8\x00\xb2\x00\xd9\x00\x86\x00'

In [55]:
# let's examine the columns we have
df.columns

Index(['rating', 'review_count', 'isbn', 'booktype', 'author_url', 'year', 'dir', 'rating_count', 'name', 'author', 'genres'], dtype='object')

In [56]:
authors = df.copy()
authors = authors[['rating','name','author']].groupby('author').agg({'rating' : np.mean,
                                                                    'name' : '|'.join})

/tmp/ipython-input-2334179269.py:2: FutureWarning: The provided callable <function mean at 0x7a9ccd36c9a0> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  authors = authors[['rating','name','author']].groupby('author').agg({'rating' : np.mean,

In [57]:
authors = authors.reset_index()
authors.head()

       author  rating                                               name
0   A_A_Milne   4.365  Winnie-the-Pooh|The House at Pooh Corner|The H...
1  A_G_Howard   4.020                        Splintered (Splintered, #1)
2  A_J_Cronin   4.220                            The Keys of the Kingdom
3  A_J_Jacobs   3.750                      The Year of Living Biblically
4    A_J_Salt   4.940                    Nik Nassa & the Mark of Destiny

In [58]:
# split the column string and make a list of string book names
authors['name'] = authors.name.str.split('|')
authors.head()

       author  rating                                               name
0   A_A_Milne   4.365  [Winnie-the-Pooh, The House at Pooh Corner, Th...
1  A_G_Howard   4.020                      [Splintered (Splintered, #1)]
2  A_J_Cronin   4.220                          [The Keys of the Kingdom]
3  A_J_Jacobs   3.750                    [The Year of Living Biblically]
4    A_J_Salt   4.940                  [Nik Nassa & the Mark of Destiny]

In [59]:
# count the books - create new column
len(authors.name[0])

6

In [60]:
authors['num_books'] = authors['name'].str.len()
authors

                     author    rating                                               name  num_books
0                 A_A_Milne  4.365000  [Winnie-the-Pooh, The House at Pooh Corner, Th...          6
1                A_G_Howard  4.020000                      [Splintered (Splintered, #1)]          1
2                A_J_Cronin  4.220000                          [The Keys of the Kingdom]          1
3                A_J_Jacobs  3.750000                    [The Year of Living Biblically]          1
4                  A_J_Salt  4.940000                  [Nik Nassa & the Mark of Destiny]          1
...                     ...       ...                                                ...        ...
2640                      _  3.988095  [Ø¹Ø²Ø§Ø²ÙÙ, Ø«ÙØ§Ø«ÙØ© ØºØ±ÙØ§Ø·Ø©, ØªØ±...         42
2641          _gota_Krist_f  4.340000           [The Notebook, The Proof, The Third Lie]          1
2642             _mile_Zola  3.990000  [Germinal (Les Rougon-Macquart, #13), L'Assomm...          4
2643  _ric_Emmanuel_Schmitt  4.160000                            [Oscar et la dame rose]          1
2644         _sne_Seierstad  3.740000                          [The Bookseller of Kabul]          1

[2645 rows x 4 columns]

In [61]:
# sort for more prolific
authors.sort_values(by='num_books', ascending=False).iloc[0]

author                                            Stephen_King
rating                                                 3.91875
name         [The Stand, The Shining (The Shining #1), It, ...
num_books                                                   56
Name: 2349, dtype: object

In [62]:
dfgb_author[['rating', 'rating_count', 'review_count', 'year']].describe()

                      rating                                                        rating_count                                                                             review_count                                                                      year
                       count      mean       std   min     25%    50%     75%   max        count          mean           std      min       25%      50%       75%       max        count         mean          std     min      25%     50%      75%     max count         mean         std     min      25%     50%      75%     max
author
A_A_Milne                6.0  4.365000  0.078677  4.25  4.3275  4.365  4.4025  4.48          6.0  47842.333333  57135.314010    544.0  15559.50  30547.0  50401.25  157833.0          6.0   543.000000   682.473150     1.0   219.50   309.5   499.25  1886.0   6.0  1944.166667   29.294482  1926.0  1926.25  1927.5  1952.75  1997.0
A_G_Howard               1.0  4.020000       NaN  4.02  4.0200  4.020  4.0200  4.02          1.0  17073.000000           NaN  17073.0  17073.00  17073.0  17073.00   17073.0          1.0  3194.000000          NaN  3194.0  3194.00  3194.0  3194.00  3194.0   1.0  2013.000000         NaN  2013.0  2013.00  2013.0  2013.00  2013.0
A_J_Cronin               1.0  4.220000       NaN  4.22  4.2200  4.220  4.2200  4.22          1.0   1015.000000           NaN   1015.0   1015.00   1015.0   1015.00    1015.0          1.0   109.000000          NaN   109.0   109.00   109.0   109.00   109.0   1.0  1941.000000         NaN  1941.0  1941.00  1941.0  1941.00  1941.0
A_J_Jacobs               1.0  3.750000       NaN  3.75  3.7500  3.750  3.7500  3.75          1.0  39489.000000           NaN  39489.0  39489.00  39489.0  39489.00   39489.0          1.0  4371.000000          NaN  4371.0  4371.00  4371.0  4371.00  4371.0   1.0  2007.000000         NaN  2007.0  2007.00  2007.0  2007.00  2007.0
A_J_Salt                 1.0  4.940000       NaN  4.94  4.9400  4.940  4.9400  4.94          1.0     16.000000           NaN     16.0     16.00     16.0     16.00      16.0          1.0     6.000000          NaN     6.0     6.00     6.0     6.00     6.0   1.0  2014.000000         NaN  2014.0  2014.00  2014.0  2014.00  2014.0
...                      ...       ...       ...   ...     ...    ...     ...   ...          ...           ...           ...      ...       ...      ...       ...       ...          ...          ...          ...     ...      ...     ...      ...     ...   ...          ...         ...     ...      ...     ...      ...     ...
_                       42.0  3.988095  0.301211  3.15  3.8000  4.075  4.2075  4.47         42.0  11574.642857   9368.218450     10.0   4724.00   8709.5  15572.75   39302.0         42.0  1437.214286  1216.421371     1.0   534.75  1020.5  1745.75  4785.0  42.0  1998.904762   18.721071  1941.0  1994.75  2007.0  2010.75  2014.0
_gota_Krist_f            1.0  4.340000       NaN  4.34  4.3400  4.340  4.3400  4.34          1.0   2628.000000           NaN   2628.0   2628.00   2628.0   2628.00    2628.0          1.0   243.000000          NaN   243.0   243.00   243.0   243.00   243.0   1.0  1986.000000         NaN  1986.0  1986.00  1986.0  1986.00  1986.0
_mile_Zola               4.0  3.990000  0.100995  3.84  3.9750  4.035  4.0500  4.05          4.0   8358.250000   4553.226942   3594.0   5181.75   8095.0  11271.50   13649.0          4.0   283.750000   171.069917   125.0   189.50   243.5   337.75   523.0   4.0  1652.500000  456.345264   968.0  1649.75  1878.5  1881.25  1885.0
_ric_Emmanuel_Schmitt    1.0  4.160000       NaN  4.16  4.1600  4.160  4.1600  4.16          1.0   6439.000000           NaN   6439.0   6439.00   6439.0   6439.00    6439.0          1.0   424.000000          NaN   424.0   424.00   424.0   424.00   424.0   1.0  2002.000000         NaN  2002.0  2002.00  2002.0  2002.00  2002.0
_sne_Seierstad           1.0  3.740000       NaN  3.74  3.7400  3.740  3.7400  3.74          1.0  24993.000000           NaN  24993.0  24993.00  24993.0  24993.00   24993.0          1.0  2088.000000          NaN  2088.0  2088.00  2088.0  2088.00  2088.0   1.0  2002.000000         NaN  2002.0  2002.00  2002.0  2002.00  2002.0

[2645 rows x 32 columns]

In [63]:
ratingdict = {}
for author, subset in dfgb_author:
    ratingdict[author] = (subset['rating'].mean(), subset['rating'].std())
ratingdict

{'A_A_Milne': (np.float64(4.364999999999999), 0.0786765530510839),
 'A_G_Howard': (np.float64(4.02), nan),
 'A_J_Cronin': (np.float64(4.22), nan),
 'A_J_Jacobs': (np.float64(3.75), nan),
 'A_J_Salt': (np.float64(4.94), nan),
 'A_Meredith_Walters': (np.float64(4.15), 0.16970562748477094),
 'A_N_Roquelaure': (np.float64(3.45), 0.2262741699796951),
 'A_S_Byatt': (np.float64(3.86), nan),
 'A_S_King': (np.float64(3.93), nan),
 'A_id_al_Qarni': (np.float64(4.050000000000001), 0.19798989873223347),
 'Abbi_Glines': (np.float64(4.179285714285713), 0.12916681436834276),
 'Abdul_Rahman_Munif': (np.float64(4.03), nan),
 'Abigail_Gibbs': (np.float64(3.82), nan),
 'Abigail_Roux': (np.float64(4.47), 0.22876479915697992),
 'Abigail_Thomas': (np.float64(3.68), nan),
 'Abolqasem_Ferdowsi': (np.float64(4.52), nan),
 'Abraham_Verghese': (np.float64(4.26), nan),
 'Abul_Hasan_Ali_Nadwi': (np.float64(4.15), nan),
 'Adam_Hochschild': (np.float64(4.14), nan),
 'Adam_Johnson': (np.float64(4.03), nan),
 'Adam_Levin': (np.float64(4.04), nan),
 'Adam_Rex': (np.float64(4.14), nan),
 'Adam_Smith': (np.float64(3.82), nan),
 'Addison_Moore': (np.float64(3.78), nan),
 'Adeline_Yen_Mah': (np.float64(4.01), nan),
 'Adolf_Hitler': (np.float64(2.97), nan),
 'Adolfo_Bioy_Casares': (np.float64(4.06), nan),
 'Aeschylus': (np.float64(3.96), nan),
 'Aesop': (np.float64(4.03), nan),
 'Agatha_Christie': (np.float64(3.9772727272727266), 0.12190905701307918),
 'Ahlam_Mosteghanemi': (np.float64(3.97), nan),
 'Ahmad_Baari': (np.float64(4.88), nan),
 'Ahmad_Fuadi': (np.float64(4.0), nan),
 'Ai_Yazawa': (np.float64(4.19), nan),
 'Aidan_Chambers': (np.float64(4.27), nan),
 'Aimee_Carter': (np.float64(3.9133333333333336), 0.13051181300301234),
 'Aimee_Friedman': (np.float64(3.64), nan),
 'Alain_Fournier': (np.float64(3.79), nan),
 'Alan_Bradley': (np.float64(3.79), nan),
 'Alan_Brennert': (np.float64(4.13), nan),
 'Alan_Campbell': (np.float64(3.58), nan),
 'Alan_Hollinghurst': (np.float64(3.65), nan),
 'Alan_Lightman': (np.float64(4.07), nan),
 'Alan_Moore': (np.float64(4.198), 0.1630030674557996),
 'Alan_Paton': (np.float64(3.83), nan),
 'Alan_Wilson_Watts': (np.float64(4.27), nan),
 'Alastair_Reynolds': (np.float64(4.09), nan),
 'Albert_Camus': (np.float64(4.032000000000001), 0.09523654760647308),
 'Albert_Einstein': (np.float64(4.13), nan),
 'Albert_Espinosa': (np.float64(3.36), nan),
 'Alcoholics_Anonymous': (np.float64(4.39), nan),
 'Aldo_Leopold': (np.float64(4.22), nan),
 'Aldous_Huxley': (np.float64(3.9400000000000004), 0.12288205727444491),
 'Aleatha_Romig': (np.float64(4.275), 0.27577164466275333),
 'Alecia_Stone': (np.float64(4.455), 0.657609306503489),
 'Aleksandr_Solzhenitsyn': (np.float64(4.0600000000000005),
  0.12288205727444532),
 'Alessandro_Baricco': (np.float64(4.036666666666666), 0.21361959960016158),
 'Alessandro_Manzoni': (np.float64(3.71), nan),
 'Alex_Flinn': (np.float64(3.8200000000000003), 0.04242640687119289),
 'Alex_Garland': (np.float64(3.5300000000000002), 0.46669047558312116),
 'Alex_Haley': (np.float64(4.39), nan),
 'Alex_Harris': (np.float64(4.11), nan),
 'Alex_Kotlowitz': (np.float64(4.23), nan),
 'Alex_Sanchez': (np.float64(3.91), 0.08485281374238578),
 'Alexander_Gordon_Smith': (np.float64(4.09), nan),
 'Alexander_Jovy': (np.float64(4.12), nan),
 'Alexander_McCall_Smith': (np.float64(3.7), nan),
 'Alexander_Pushkin': (np.float64(4.03), nan),
 'Alexandra_Adornetto': (np.float64(3.8666666666666667), 0.16441816606851367),
 'Alexandra_Bracken': (np.float64(4.2), 0.3269556544854364),
 'Alexandra_Fuller': (np.float64(3.94), nan),
 'Alexandra_Ivy': (np.float64(3.9899999999999998), 0.21213203435596414),
 'Alexandra_Monir': (np.float64(3.88), nan),
 'Alexandra_Potter': (np.float64(3.18), nan),
 'Alexandra_Ripley': (np.float64(3.23), nan),
 'Alexandre_Dumas': (np.float64(4.09), 0.08485281374238578),
 'Alexandre_Dumas_fils': (np.float64(3.94), nan),
 'Alexei_Maxim_Russell': (np.float64(4.17), 0.6298412498399895),
 'Alexis_de_Tocqueville': (np.float64(3.94), nan),
 'Alfred_Bester': (np.float64(4.075), 0.10606601717798238),
 'Alfred_Lansing': (np.float64(4.31), nan),
 'Alfred_Tennyson': (np.float64(4.04), nan),
 'Ali_Marsman': (np.float64(4.1), nan),
 'Ali_Smith': (np.float64(3.46), nan),
 'Alice_Clayton': (np.float64(4.19), nan),
 'Alice_Hoffman': (np.float64(3.7942857142857145), 0.11602544876838351),
 'Alice_Kuipers': (np.float64(3.65), nan),
 'Alice_Schroeder': (np.float64(4.03), nan),
 'Alice_Sebold': (np.float64(3.725), 0.007071067811865324),
 'Alice_Walker': (np.float64(4.074999999999999), 0.07778174593052045),
 'Alija_Izetbegovi_': (np.float64(4.46), nan),
 'Alison_Bechdel': (np.float64(4.12), nan),
 'Alison_Croggon': (np.float64(4.2175), 0.2766917659297678),
 'Alison_Goodman': (np.float64(4.0649999999999995), 0.0919238815542511),
 'Alison_Weir': (np.float64(3.9899999999999998), 0.08888194417315584),
 'Alistair_MacLeod': (np.float64(3.98), nan),
 'Allan_Frewin_Jones': (np.float64(3.795), 0.28991378028648457),
 'Allan_Gurganus': (np.float64(3.83), nan),
 'Allan_Pease': (np.float64(3.94), nan),
 'Allegra_Goodman': (np.float64(3.67), nan),
 'Allen_Ginsberg': (np.float64(4.15), nan),
 'Ally_Carter': (np.float64(4.197777777777778), 0.21194207804125262),
 'Ally_Condie': (np.float64(3.6133333333333333), 0.1040832999733067),
 'Ally_Shields': (np.float64(3.83), nan),
 'Allyse_Near': (np.float64(4.26), nan),
 'Alma_Katsu': (np.float64(3.69), nan),
 'Alyson_Noel': (np.float64(3.772), 0.17516975893242662),
 'Alyxandra_Harvey': (np.float64(4.03), 0.1153256259467082),
 'Am_lie_Nothomb': (np.float64(3.77), 0.08485281374238578),
 'Amanda_E_Alvarez': (np.float64(3.77), nan),
 'Amanda_Hocking': (np.float64(3.95375), 0.12993817211054096),
 'Amber_Argyle': (np.float64(3.69), nan),
 'Amber_Lea_Easton': (np.float64(4.21), nan),
 'Ambrose_Bierce': (np.float64(4.15), nan),
 'Amelia_Atwater_Rhodes': (np.float64(4.041666666666667), 0.13090709173557669),
 'Amelia_Hutchins': (np.float64(4.38), 0.19798989873223286),
 'Ami_McKay': (np.float64(3.97), nan),
 'Amin_Maalouf': (np.float64(4.17), nan),
 'Amish_Tripathi': (np.float64(3.93), 0.0),
 'Amitav_Ghosh': (np.float64(3.91), nan),
 'Amor_Towles': (np.float64(3.98), nan),
 'Amy_A_Bartol': (np.float64(4.3375), 0.16680827317612265),
 'Amy_Efaw': (np.float64(3.72), nan),
 'Amy_Harmon': (np.float64(4.365), 0.14849242404917495),
 'Amy_Hempel': (np.float64(4.27), nan),
 'Amy_Plum': (np.float64(4.105), 0.12020815280171367),
 'Amy_Tan': (np.float64(3.8200000000000003), 0.24361855430159662),
 'Anastacia_Moore': (np.float64(4.65), nan),
 'Anchee_Min': (np.float64(3.86), nan),
 'Andr_Aciman': (np.float64(4.04), nan),
 'Andr_Gide': (np.float64(3.67), nan),
 'Andre_Agassi': (np.float64(4.11), nan),
 'Andre_Dubus_III': (np.float64(3.77), nan),
 'Andrea_Cremer': (np.float64(4.066666666666666), 0.055075705472860864),
 'Andrea_Hirata': (np.float64(3.94), 0.2764054992217052),
 'Andrea_Levy': (np.float64(3.86), nan),
 'Andrew_Clements': (np.float64(3.8266666666666667), 0.05859465277082333),
 'Andrew_Davidson': (np.float64(3.96), nan),
 'Andrew_Klavan': (np.float64(4.12), 0.1838477631085022),
 'Andrew_Smith': (np.float64(4.17), nan),
 'Andrzej_Sapkowski': (np.float64(4.273333333333333), 0.11060440015358027),
 'Andy_Szpuk': (np.float64(4.18), nan),
 'Andy_Weir': (np.float64(4.33), nan),
 'Angel_Sefer': (np.float64(4.43), nan),
 'Angela_Carter': (np.float64(4.01), 0.0707106781186545),
 'Angela_Morrison': (np.float64(4.0), nan),
 'Angelo_Tsanatelis': (np.float64(4.1899999999999995), 0.21213203435596412),
 'Angie_Martin': (np.float64(4.4399999999999995), 0.11313708498984708),
 'Angie_Sage': (np.float64(3.865), 0.134350288425444),
 'Anita_Diamant': (np.float64(4.13), nan),
 'Anita_Shreve': (np.float64(3.84), nan),
 'Ann_Aguirre': (np.float64(4.025), 0.14849242404917495),
 'Ann_Brashares': (np.float64(3.742857142857143), 0.10291003930849597),
 'Ann_Fairbairn': (np.float64(4.41), nan),
 'Ann_M_Martin': (np.float64(4.16), nan),
 'Ann_Marie_MacDonald': (np.float64(3.91), nan),
 'Ann_Patchett': (np.float64(3.78), 0.1513274595042156),
 'Ann_Rule': (np.float64(4.029999999999999), 0.12186057606953923),
 'Anna_Banks': (np.float64(4.0600000000000005), 0.014142135623731277),
 'Anna_Carey': (np.float64(3.8200000000000003), 0.1555634918610406),
 'Anna_Gavalda': (np.float64(4.1), nan),
 'Anna_Godbersen': (np.float64(3.7866666666666666), 0.12701705922171752),
 'Anna_Lee_Waldo': (np.float64(4.2), nan),
 'Anna_Quindlen': (np.float64(3.81), nan),
 'Anna_Sewell': (np.float64(3.92), nan),
 'Anne_Bishop': (np.float64(4.253), 0.14735067771212387),
 'Anne_Bront_': (np.float64(3.7249999999999996), 0.19091883092036785),
 'Anne_Carson': (np.float64(4.39), nan),
 'Anne_Elisabeth_Stengl': (np.float64(4.18), 0.39509492530276813),
 'Anne_Fadiman': (np.float64(4.12), nan),
 'Anne_Fortier': (np.float64(3.9), nan),
 'Anne_Frank': (np.float64(4.06), nan),
 'Anne_Lamott': (np.float64(4.18), 0.042426406871192576),
 'Anne_McCaffrey': (np.float64(4.033076923076924), 0.1835022531825615),
 'Anne_Michaels': (np.float64(3.96), nan),
 'Anne_Morrow_Lindbergh': (np.float64(4.18), nan),
 'Anne_Rice': (np.float64(3.812105263157895), 0.14401307607947048),
 'Anne_Tyler': (np.float64(3.8316666666666666), 0.16702295251451718),
 'Annemarie_Selinko': (np.float64(3.94), nan),
 'Annette_Curtis_Klause': (np.float64(3.7), 0.09899494936611673),
 'Annie_Dillard': (np.float64(3.98), 0.19798989873223347),
 'Annie_Proulx': (np.float64(3.8449999999999998), 0.10606601717798206),
 'Anonymous': (np.float64(4.265294117647059), 0.3613363676524068),
 'Anthony_Bourdain': (np.float64(3.97), nan),
 'Anthony_Burgess': (np.float64(4.055), 0.14849242404917495),
 'Anthony_Doerr': (np.float64(4.19), nan),
 'Anthony_Hope': (np.float64(3.87), nan),
 'Anthony_Horowitz': (np.float64(4.0672727272727265), 0.08462752614733685),
 'Anthony_Kiedis': (np.float64(4.06), nan),
 'Anthony_Marra': (np.float64(4.15), nan),
 'Anthony_Ryan': (np.float64(4.54), nan),
 'Anthony_Swofford': (np.float64(3.59), nan),
 'Anthony_Trollope': (np.float64(4.01), 0.028284271247461926),
 'Antoine_de_Saint_Exup_ry': (np.float64(4.293333333333333),
  0.1365039681962884),
 'Anton_Chekhov': (np.float64(4.06), 0.35791060336346536),
 'Antonia_Fraser': (np.float64(3.89), nan),
 'Antonia_Michaelis': (np.float64(4.14), nan),
 'Antony_Beevor': (np.float64(4.28), nan),
 'Anya_Seton': (np.float64(4.18), nan),
 'Aporva_Kala': (np.float64(4.355), 0.10606601717798175),
 'April_Henry': (np.float64(3.94), nan),
 'Aprilynne_Pike': (np.float64(4.0225), 0.19720970226301415),
 'Aravind_Adiga': (np.float64(3.69), nan),
 'Ariana_Franklin': (np.float64(3.94), nan),
 'Aristophanes': (np.float64(3.82), nan),
 'Aristotle': (np.float64(3.88), nan),
 'Arkady_Strugatsky': (np.float64(4.275), 0.06363961030678918),
 'Armando_Cosani': (np.float64(4.55), nan),
 'Armistead_Maupin': (np.float64(4.07), nan),
 'Art_Spiegelman': (np.float64(4.426666666666667), 0.07767453465154048),
 'Arthur_C_Clarke': (np.float64(3.9659999999999997), 0.17285832349065502),
 'Arthur_Conan_Doyle': (np.float64(4.198461538461538), 0.2004098364953741),
 'Arthur_Golden': (np.float64(4.03), nan),
 'Arthur_Koestler': (np.float64(4.03), nan),
 'Arthur_Miller': (np.float64(3.47), 0.028284271247461926),
 'Arthur_Ransome': (np.float64(3.97), nan),
 'Arthur_Rimbaud': (np.float64(4.3933333333333335), 0.0461880215351701),
 'Arthur_Schnitzler': (np.float64(3.79), nan),
 'Arturo_P_rez_Reverte': (np.float64(3.8049999999999997),
  0.007071067811865638),
 'Arun_Tiwari': (np.float64(4.1), nan),
 'Arundhati_Roy': (np.float64(3.88), nan),
 'Asa_Don_Brown': (np.float64(4.45), nan),
 'Ashley_Chappell': (np.float64(4.605), 0.26162950903902266),
 'Ashley_Waelti': (np.float64(4.36), nan),
 'Astrid_Lindgren': (np.float64(4.1899999999999995), 0.12000000000000009),
 'Audrey_Niffenegger': (np.float64(3.565), 0.5020458146424487),
 'Augusten_Burroughs': (np.float64(3.815), 0.23334523779156074),
 'Augustine_of_Hippo': (np.float64(3.82), nan),
 'Aurora_Rose_Reynolds': (np.float64(4.21), nan),
 'Austin_Kleon': (np.float64(3.88), nan),
 'Author_Neva_Squires_Rodriguez': (np.float64(4.25), nan),
 'Autumn_Cornwell': (np.float64(3.95), nan),
 'Avery_Aster': (np.float64(3.73), 0.3144307024873154),
 'Avi': (np.float64(3.79), nan),
 'Ayaan_Hirsi_Ali': (np.float64(4.18), nan),
 'Ayn_Rand': (np.float64(3.7979999999999996), 0.1739827577663947),
 'Azar_Nafisi': (np.float64(3.54), nan),
 'B_Kristin_McMichael': (np.float64(3.8700000000000006), 0.14106735979665874),
 'Banana_Yoshimoto': (np.float64(3.82), nan),
 'Barack_Obama': (np.float64(3.66), nan),
 'Barbara_Demick': (np.float64(4.41), nan),
 'Barbara_Ehrenreich': (np.float64(3.58), nan),
 'Barbara_Erskine': (np.float64(4.04), nan),
 'Barbara_Kingsolver': (np.float64(3.931666666666666), 0.11321071798494443),
 'Barbara_Taylor_Bradford': (np.float64(4.12), nan),
 'Barbara_W_Tuchman': (np.float64(4.126666666666666), 0.08082903768654764),
 'Barry_Jordan_Jr_': (np.float64(4.48), nan),
 'Barry_Lyga': (np.float64(3.99), nan),
 'Barry_Unsworth': (np.float64(4.12), nan),
 'Beatrice_Sparks': (np.float64(3.76), nan),
 'Beatrix_Potter': (np.float64(4.24), 0.14142135623730964),
 'Becca_Fitzpatrick': (np.float64(4.24), 0.18264720090929407),
 'Belle_Aurora': (np.float64(4.255), 0.12020815280171303),
 'Belsebuub': (np.float64(4.62), nan),
 'Belzebuub': (np.float64(4.475), 0.0919238815542511),
 'Ben_Goldacre': (np.float64(4.07), nan),
 'Ben_Peller': (np.float64(4.18), 0.21213203435596412),
 'Ben_Sherwood': (np.float64(3.99), nan),
 'Benedict_Freedman': (np.float64(4.12), nan),
 'Benjamin_Alire_S_enz': (np.float64(4.27), nan),
 'Benjamin_Franklin': (np.float64(3.78), nan),
 'Benjamin_Graham': (np.float64(4.24), nan),
 'Benjamin_Hoff': (np.float64(4.0600000000000005), 0.08485281374238578),
 'Bernadette_Azizi': (np.float64(4.06), nan),
 'Bernard_Cornwell': (np.float64(4.123333333333333), 0.22327113561766107),
 'Bernard_Malamud': (np.float64(3.77), 0.2262741699796954),
 'Bernhard_Schlink': (np.float64(3.69), nan),
 'Bertolt_Brecht': (np.float64(3.66), nan),
 'Bertrand_Russell': (np.float64(4.02), nan),
 'Beryl_Markham': (np.float64(4.18), nan),
 'Bess_Streeter_Aldrich': (np.float64(4.07), nan),
 'Beth_Fantaskey': (np.float64(3.86), nan),
 'Beth_Hoffman': (np.float64(3.89), nan),
 'Beth_Revis': (np.float64(3.94), 0.19798989873223347),
 'Bethany_Hamilton': (np.float64(4.12), nan),
 'Bette_Greene': (np.float64(3.63), nan),
 'Betty_Edwards': (np.float64(3.86), nan),
 'Betty_Friedan': (np.float64(3.81), nan),
 'Betty_MacDonald': (np.float64(4.15), nan),
 'Betty_Mahmoody': (np.float64(3.99), nan),
 'Betty_Smith': (np.float64(4.22), nan),
 'Bev_Stout': (np.float64(4.4), nan),
 'Bill_Bryson': (np.float64(3.963333333333333), 0.10535653752852739),
 'Bill_Courtney': (np.float64(4.39), nan),
 'Bill_Konigsberg': (np.float64(4.05), nan),
 'Bill_Martin_Jr_': (np.float64(4.16), nan),
 'Bill_Watterson': (np.float64(4.690000000000001), 0.060415229867972826),
 'Billie_Letts': (np.float64(3.97), nan),
 'Bisco_Hatori': (np.float64(4.35), nan),
 'Blue_Jeans': (np.float64(4.15), nan),
 'Bo_Hampton': (np.float64(3.94), nan),
 'Bob_Atkinson': (np.float64(4.15), nan),
 'Bob_Dylan': (np.float64(3.99), nan),
 'Bodie_Thoene': (np.float64(4.336666666666666), 0.06806859285554051),
 'Bohumil_Hrabal': (np.float64(4.16), 0.05656854249492385),
 'Boris_Pasternak': (np.float64(4.02), nan),
 'Boris_Vian': (np.float64(4.035), 0.0212132034355966),
 'Brae_Wyckoff': (np.float64(3.92), nan),
 'Bram_Stoker': (np.float64(3.94), nan),
 'Brandon_Mull': (np.float64(4.211666666666666), 0.15419684389333865),
 'Brandon_Sanderson': (np.float64(4.316363636363636), 0.2578089497000725),
 'Bree_Despain': (np.float64(3.945), 0.1626345596729056),
 'Brenna_Yovanoff': (np.float64(3.58), nan),
 'Brent_Weeks': (np.float64(4.300000000000001), 0.11882760622010352),
 'Bret_Easton_Ellis': (np.float64(3.62), 0.13656500283747663),
 'Brett_Axel': (np.float64(4.61), nan),
 'Brian_Celio': (np.float64(4.05), nan),
 'Brian_Greene': (np.float64(4.1), nan),
 'Brian_Jacques': (np.float64(4.009285714285714), 0.07205385653633149),
 'Brian_K_Vaughan': (np.float64(4.15), nan),
 'Brian_Katcher': (np.float64(3.89), nan),
 'Brian_L_Weiss': (np.float64(4.16), nan),
 'Brian_Lumley': (np.float64(3.96), nan),
 'Brian_Patrick_McKinley': (np.float64(4.53), nan),
 'Brian_Selznick': (np.float64(4.175), 0.06363961030678918),
 'Brigid_Kemmerer': (np.float64(4.125), 0.1484924240491756),
 'Brodi_Ashton': (np.float64(3.81), nan),
 'Brom': (np.float64(4.09), nan),
 'Brother_Andrew': (np.float64(4.29), nan),
 'Brother_Lawrence': (np.float64(4.31), nan),
 'Bruce_Campbell': (np.float64(4.01), nan),
 'Bruno_Schulz': (np.float64(4.2), nan),
 'Bryan_Davis': (np.float64(4.17), nan),
 'Bryan_Lee_O_Malley': (np.float64(4.24), 0.09899494936611643),
 'Bryce_Courtenay': (np.float64(4.125), 0.15631165450257803),
 'CLAMP': (np.float64(4.12), nan),
 'C_C_Humphreys': (np.float64(3.82), nan),
 'C_C_Hunter': (np.float64(4.322), 0.10183319694480758),
 'C_D_Payne': (np.float64(4.03), nan),
 'C_E_Kilgore': (np.float64(3.96), nan),
 'C_G_Jung': (np.float64(4.18), nan),
 'C_J_Box': (np.float64(3.8), nan),
 'C_J_Daugherty': (np.float64(4.105), 0.1343502884254443),
 'C_J_Redwine': (np.float64(3.74), nan),
 'C_J_Roberts': (np.float64(4.27), 0.1664331697709322),
 'C_J_Sansom': (np.float64(4.06), nan),
 'C_L_Stone': (np.float64(4.416666666666667), 0.10969655114602912),
 'C_L_Wilson': (np.float64(4.239999999999999), 0.13076696830622028),
 'C_S_Lewis': (np.float64(4.056111111111111), 0.13856996062252486),
 'Caleb_Carr': (np.float64(4.03), nan),
 'Candace_Bushnell': (np.float64(3.56), nan),
 'Candice_Millard': (np.float64(4.17), nan),
 'Cao_Xueqin': (np.float64(4.05), nan),
 'Cara_Lynn_Shultz': (np.float64(3.91), nan),
 'Caragh_M_O_Brien': (np.float64(3.92), nan),
 'Carl_Hiaasen': (np.float64(3.8099999999999996), 0.04242640687119289),
 'Carl_Sagan': (np.float64(4.26), 0.12549900398011124),
 'Carla_Capshaw': (np.float64(4.29), 0.03605551275463999),
 'Carlo_Collodi': (np.float64(3.83), nan),
 'Carlos_Castaneda': (np.float64(3.91), nan),
 'Carlos_Rivera': (np.float64(4.53), nan),
 'Carlos_Ruiz_Zaf_n': (np.float64(3.89), 0.25910100990411694),
 'Carol_E_Wyer': (np.float64(4.25), nan),
 'Carol_Plum_Ucci': (np.float64(4.06), nan),
 'Carol_Rifka_Brunt': (np.float64(4.04), nan),
 'Carol_Shields': (np.float64(3.79), nan),
 'Carole_Wilkinson': (np.float64(3.94), nan),
 'Carolina_Andujar': (np.float64(4.32), nan),
 'Caroline_B_Cooney': (np.float64(3.7), nan),
 'Carolyn_Jessop': (np.float64(3.94), nan),
 'Carolyn_Keene': (np.float64(3.935), 0.0212132034355966),
 'Carolyn_Turgeon': (np.float64(3.6), nan),
 'Carrie_Jones': (np.float64(3.9033333333333338), 0.16502525059315412),
 'Carrie_Ryan': (np.float64(3.8633333333333333), 0.22744962812309308),
 'Carrie_Vaughn': (np.float64(3.66), nan),
 'Carson_McCullers': (np.float64(3.9133333333333336), 0.11239810200058233),
 'Cassandra_Clare': (np.float64(4.428461538461539), 0.18876114332872967),
 'Cat_Clarke': (np.float64(3.85), 0.1131370849898477),
 'Cat_Patrick': (np.float64(3.825), 0.007071067811865638),
 'Cate_Tiernan': (np.float64(4.085), 0.07778174593051983),
 'Cath_Crowley': (np.float64(3.89), nan),
 'Catherine_Anderson': (np.float64(4.21), 0.05873670062235346),
 'Catherine_Fisher': (np.float64(3.67), 0.04242640687119289),
 'Catherine_Gilbert_Murdock': (np.float64(3.72), nan),
 'Catherine_Hardwicke': (np.float64(4.13), nan),
 'Catherine_Jinks': (np.float64(3.79), nan),
 'Catherine_Marshall': (np.float64(4.16), nan),
 'Catherynne_M_Valente': (np.float64(4.096666666666667), 0.09451631252505201),
 'Cecelia_Ahern': (np.float64(3.85), 0.12708265027138832),
 'Cecily_von_Ziegesar': (np.float64(3.6233333333333335), 0.13613718571108077),
 'Celia_Rees': (np.float64(3.82), nan),
 'Celso_Cukierkorn': (np.float64(4.15), nan),
 'Chad_Harbach': (np.float64(3.99), nan),
 'Chaim_Potok': (np.float64(4.05), 0.10099504938362074),
 'Chanda_Hahn': (np.float64(3.995), 0.16263455967290624),